# Generated by Django 3.0.2 on 2020-02-16 17:09

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
    ]
