# Generated by Django 3.0.2 on 2020-02-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200216_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Daniel Mössner', max_length=200),
            preserve_default=False,
        ),
    ]
