# Generated by Django 3.0.2 on 2020-02-17 14:29

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200216_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', martor.models.MartorField()),
            ],
            options={
                'verbose_name': 'Leistung',
                'verbose_name_plural': 'Leistungen',
            },
        ),
    ]
