# Generated by Django 3.0.2 on 2020-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
