# Generated by Django 3.0.2 on 2020-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200217_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo Einstellung', 'verbose_name_plural': 'Seo Einstellungen'},
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(max_length=160, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_tag',
            field=models.CharField(max_length=60, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='url',
            field=models.CharField(blank=True, help_text='Aktiviert sich bei dieser Url. Wenn leer immer aktiv.', max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
