# Generated by Django 3.0.2 on 2020-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200224_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Beschreibung'),
        ),
    ]
