# Generated by Django 3.0.2 on 2020-02-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200224_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textblock',
            options={'ordering': ['key'], 'verbose_name': 'Textbaustein', 'verbose_name_plural': 'Textbausteine'},
        ),
    ]
